# Type of space (only influences which agents meet)
# Possible values: "random", "grid", "network"
SPACE_TYPE: "grid"

# Threshold
# tau > 0
TAU: 0.3

# Adjustment parameter
# 0 < mu < 0.5
MU: 0.4

# Number of agents
NUMBER_AGENTS: 2

GRID_SIZE: 5

# Neighborhood definition
# TRUE: 8 neighboring cells
# FALSE: 4 neighboring cells
MOORE_NEIGHBORHOOD: FALSE

