# Type of space (only influences which agents meet)
# Possible values: "random", "grid", "network"
SPACE_TYPE: "grid"

# Threshold
# tau > 0
TAU: 0.3

# Adjustment parameter
# 0 < mu < 0.5
MU: 0.4

# Number of agents
NUMBER_AGENTS: 200

GRID_SIZE: 50

# Neighborhood definition
# TRUE: Moore neighborhood
# FALSE: Von-Neumann neighborhood
MOORE_NEIGHBORHOOD: FALSE

# After how many steps a lineplot of all agents should be plotted
PLOT_AFTER: 1000
