# Type of space (only influences which agents meet)
# Possible values: "random", "grid", "network"
SPACE_TYPE: "grid"

# Threshold
# tau > 0
TAU: 0.4

# Adjustment parameter
# 0 < mu < 0.5
MU: 0.4

# Adjust standard deviation
SIGMA: 0.4

# Number of agents
NUMBER_AGENTS: 30

GRID_SIZE: 10

# Neighborhood definition
# TRUE: Moore neighborhood
# FALSE: Von-Neumann neighborhood
MOORE_NEIGHBORHOOD: TRUE


# After how many steps a lineplot of all agents should be plotted
PLOT_AFTER: 500

#Network properties:
AVERAGE_NODE_DEGREE: 2

#optional future settings for watts strogatz graph:
REWIRING_PROBABILITY: 0.6
