# Type of space (only influences which agents meet)
# Possible values: "random", "grid", "network"
SPACE_TYPE: "random"

# Threshold
# tau > 0
TAU: 0.2

# Adjustment parameter
# 0 < mu < 0.5
MU: 0.4

# Number of agents
NUMBER_AGENTS: 30

# Number of cells on each grid side
GRID_SIZE: 10

# Initial opinion variance
SIGMA: 0.2

# Neighborhood definition
# TRUE: Moore neighborhood
# FALSE: Von-Neumann neighborhood
MOORE_NEIGHBORHOOD: FALSE


# After how many steps a lineplot of all agents should be plotted
PLOT_AFTER: 100

# Network properties:
AVERAGE_NODE_DEGREE: 3

# Optional future settings for watts strogatz graph:
REWIRING_PROBABILITY: 0.6
